name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t prism-image .

      # Step 3: Run Docker container and execute prism.py
      - name: Run Docker container
        run: |
          docker run --rm -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
                     -e GITHUB_EVENT_PULL_REQUEST_NUMBER=${{ github.event.pull_request.number }} \
                     -e GITHUB_REPOSITORY=${{ github.repository }} \
                     --env-file .env \
                     prism-image
